[ hosting ]
public = "."
ignore = ["firebase.json", "**/.*", "**/node_modules/**"]

[ hosting.rewrites ]
source = "**"
destination = "/index.html"

[ hosting.headers ]
source = "**"
headers = [
  { key = "Cache-Control", value = "no-cache, no-store, must-revalidate" }
]

[ firestore ]
rules = "firestore.rules"
indexes = "firestore.indexes.json"